In [1]:
import pandas as pd
import numpy
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif

In [2]:
df = pd.read_csv('heart.csv')

In [3]:
df['target'].value_counts()

1    165
0    138
Name: target, dtype: int64

In [5]:

dataframe = df
array = dataframe.values

X = array[:,0:13]
Y = array[:,13]

# feature extraction
test = SelectKBest(score_func=f_classif, k=4)
fit = test.fit(X, Y)

# summarize scores
pd.set_option('precision', 3)
print(fit.scores_)
features = fit.transform(X)

# summarize selected features
print(features[0:5,:])

[16.11669982 25.79219115 69.77227149  6.45816867  2.20298345  0.23694234
  5.77720891 65.1201044  70.95243822 68.55143941 40.90207063 54.5598338
 40.40769615]
[[  3.  150.    0.    2.3]
 [  2.  187.    0.    3.5]
 [  1.  172.    0.    1.4]
 [  1.  178.    0.    0.8]
 [  0.  163.    1.    0.6]]


In [6]:
#X = df[['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach','exang', 'oldpeak', 'slope', 'ca', 'thal']]
X = df[[ 'cp','thalach','exang', 'oldpeak', ]]
y = df['target']

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [8]:
from sklearn import svm
clf = svm.SVC(kernel='linear')
clf.fit(X_train, y_train)

SVC(kernel='linear')

In [9]:
from sklearn.metrics import accuracy_score
y_pred = clf.predict(X_test)
accuracy_score(y_test, y_pred)

0.819672131147541

In [10]:
import pickle
filename = 'model.sav'
pickle.dump(clf, open(filename, 'wb'))

In [11]:
df[[ 'cp','thalach','exang', 'oldpeak', ]].loc[0]

cp           3.0
thalach    150.0
exang        0.0
oldpeak      2.3
Name: 0, dtype: float64

In [12]:
clf.predict([[3,150,0,2.3]])

array([1], dtype=int64)